apps/citas/urls.py
from django.urls import path, re_path
from .views import citas_agregar_views, agendar_create_view1, citas_list_view, all_events, CalendarioListView, CitaCreateView
from django.contrib.auth.decorators import login_required

app_name = 'citas'

urlpatterns = [
    path(
        'agregar/', 
        login_required(agendar_create_view1),
        name = 'agregar_citas'
    ),
    path(
        'editar/<int:id>/', 
        login_required(agendar_create_view1),
        name='confirmar_cita'
    ),
    path(
        'listar/', 
        login_required(citas_list_view),
        name='listar_cita'
    ),
    path(
        'calendario/', 
        login_required(CalendarioListView.as_view()),
        name='calendario'
    ),
    re_path('^all_events', all_events, name='all_events'),
]

clinica/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path, re_path


urlpatterns = [
    path('', include('apps.access.urls')),
    path('admin/', admin.site.urls),
    path('citas/', include('apps.citas.urls')),
    path('medico/', include('apps.medico.urls')),
    path('login/', include('apps.cliente.urls')),
]

apps/citas/models.py
from django.db import models
from apps.cliente.models import Usuario
# Create your models here.
class Agenda(models.Model):
    
    cliente = models.ForeignKey(Usuario, models.DO_NOTHING, db_column='id_usuario')
    fecha = models.DateField(blank=False, null=False)
    desde = models.TimeField(blank=False, null=False)
    hasta = models.TimeField(blank=False, null=False)
    comentario = models.CharField(max_length=100, blank=True, null=True)
    estado = models.CharField(max_length=100,blank=True, null=True)
    created = models.DateTimeField(blank=False, null=False, auto_now_add=True)
    
    def __str__(self):
        return self.comentario
    class Meta:
        managed = False
        db_table = 'agenda'

apps/citas/forms.py
from django import forms

from .models import Agenda

import datetime

from apps.cliente.models import Usuario

class CitaUpdateForm(forms.ModelForm):
    
    comentario = forms.CharField(widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):   
        super(CitaUpdateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-control'
        self.fields["comentario"].widget.attrs['rows'] = 3
        self.fields['fecha'].widget.attrs['class'] = 'form-control flatpickr-basic flatpickr-input'
        self.fields['desde'].widget.attrs['class'] = 'form-control flatpickr-time text-start flatpickr-input active'
        self.fields['hasta'].widget.attrs['class'] = 'form-control flatpickr-time text-start flatpickr-input active'
        

    class Meta:
        model = Agenda
        fields = [
            'fecha',
            'desde',
            'hasta',
            'comentario',

        ]

apps/citas/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import CitaUpdateForm
from django.core.paginator import Paginator
from django.conf import settings
from django.core.mail import send_mail
from django.db.models import Q, F
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
)
from .models import Agenda
from apps.cliente.models import Usuario
from datetime import datetime
from django.http import HttpResponse, JsonResponse
import json

# Create your views here.
@login_required(login_url='/')
def citas_agregar_views(request):
    template_name = 'calendario.html'
    context = {}
    return render(request, template_name, context)

class CalendarioListView(ListView):
    model = Agenda
    template_name = 'calendario.html'
    context_object_name = 'agenda'

    def get_queryset(self):
        cliente_id = self.request.user.id
        return Agenda.objects.filter(cliente=cliente_id)

def enviar_correo(mensaje,correo_destino, usuario, motivo):
    subject = 'cita'
    message = f'Estimado {user.username}, su cita para {motivo} se ha realizado espere confirmacion.'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [correo_destino, ]
    send_mail( subject, message, email_from, recipient_list )
    return 

class CitaCreateView(CreateView):

    template_name = 'agendar_cita.html'
    model = Agenda
    form_class = CitaUpdateForm
    success_url = reverse_lazy('citas:listar_cita')

    def form_valid(self, form):
        cliente = Usuario.objects.get(id=int(self.request.user.id))
        print(cliente)
        form_cita = form.save(commit=False)
        fecha = form.cleaned_data.get('fecha')
        desde= form.cleaned_data.get('desde')
        hasta = form.cleaned_data.get('hasta')
        agenda1=Agenda.objects.filter(Q(fecha=fecha),Q(desde__lte=desde, hasta__gte=desde)|Q(desde__lte=hasta,hasta__gte=hasta)|Q(desde__gte=desde,hasta__lte=hasta))
        if agenda1:
            print(agenda1)
            return super(CitaCreateView, self).form_invalid(form)
        else:
            pass
        #print(citas_agendadas.comentario)
        comentario = form.cleaned_data.get('comentario')
        estado = 'BORRADOR'
        form_cita.cliente=cliente
        form_cita.estado=estado
        #form_cita.save()     

        return super(CitaCreateView, self).form_valid(form)
 
    # specify the model for create view
    
 
    # specify the fields to be displayed
 


@login_required
def agendar_create_view1(request, id=None):
    template_name = 'agendar_cita.html'

    #cliente_id = request.user.id
    cliente = Usuario.objects.get(id=int(request.user.id))
    #Empresa.objects.get(razon_social=request.session['empresa_name'])
    #print(cliente_id)
    if id:
        agenda_medica = get_object_or_404(Agenda, pk=id)
        estado_boton=agenda_medica.estado
        form = CitaUpdateForm(request.POST or None, instance = agenda_medica)

    else:
        form = CitaUpdateForm(request.POST or None)
        estado_boton=None

    if request.method == 'POST':

        if form.is_valid():

            if 'btn_agregar_agenda' in request.POST:
                fecha = form.cleaned_data.get('fecha')
                desde = form.cleaned_data.get('desde')
                hasta = form.cleaned_data.get('hasta')
                comentario = form.cleaned_data.get('comentario')
                estado = form.cleaned_data.get('estado')
                agenda1 = Agenda.objects.filter(Q(fecha=fecha), (Q(desde__gte=desde, desde__lt=hasta)|Q(hasta__gt=desde, hasta__lte=hasta)))
                if agenda1:
                    print(agenda1)
                    return render(request,'agendar_cita.html',{
                        'error':'existe agenda',
                        'form': form,
                        'id': id,
                        'estado_boton': estado_boton,
                        })
                else:
                    citas = Agenda.objects.create(
                        cliente = cliente,
                        fecha = fecha,
                        desde = desde,
                        hasta = hasta,
                        comentario = comentario,
                        estado = 'BORRADOR',
                        
                    )
                
                    #pass
                    citas.save()
                    subject = 'cita'
                    message = f'Estimado {cliente}, su cita para {comentario} se ha realizado espere confirmacion.'
                    email_from = settings.EMAIL_HOST_USER
                    recipient_list = [cliente.correo, ]
                    send_mail( subject, message, email_from, recipient_list )
                    return redirect('citas:confirmar_cita', id=citas.id)

            if 'btn_confirmar_agenda' in request.POST:
                form_agenda = form.save(commit=False)
                fecha=form.cleaned_data.get('fecha')
                desde = form.cleaned_data.get('desde')
                comentario = form.cleaned_data.get('comentario')
                form_agenda.estado = 'CONFIRMADO'
                form_agenda.save()
                subject = 'confirmacion_cita'
                message = f'Estimado {cliente}, su cita para {comentario} esta registrada para la fecha {fecha} a las {desde}. Por favor llegar 15 minutos antes'
                email_from = settings.EMAIL_HOST_USER
                recipient_list = [cliente.correo, ]
                send_mail( subject, message, email_from, recipient_list )

                return redirect('citas:listar_cita')

            if 'btn_cancelar_agenda' in request.POST:
                form_agenda = form.save(commit=False)
                form_agenda.estado = 'CANCELADA'
                form_agenda.save()

                return redirect('citas:listar_cita')
            
            if 'btn_atender_agenda' in request.POST:
                form_agenda = form.save(commit=False)
                form_agenda.estado = 'ATENDIDA'
                form_agenda.save()

                return redirect('citas:listar_cita')

    context = {
        'form':form,
        'id':id,
        'estado_boton':estado_boton,
    }
    return render(request, template_name, context)

def citas_list_view(request):
    
    cliente_id = request.user.id
    query = request.GET.get('busqueda',None)

    if query is not None:
        agenda = Agenda.objects.filter(Q(empresa__id=empresa_id),Q(cliente__razon_social_comprador__icontains=query)).order_by('fecha_desde')
        
    else:
        agenda = Agenda.objects.filter(cliente=cliente_id).order_by('fecha')
    
    p = Paginator(agenda, 5)
    template_name = 'listar_cita.html' 
    

    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)

    context = {
        'page_obj': page_obj,
        
    }
    return render(request, template_name, context)



# Display all events.
def all_events(request):  
    cliente_id = request.user.id
    all_events = Agenda.objects.filter(cliente=cliente_id) 
                                                                                    
    out = []                                                                                                             
    for event in all_events:  
        if event.estado == "CANCELADA":
            color = 'rgb(255,51,51)'
        elif event.estado == "CONFIRMADO":
            color = 'rgb(136,255,77)'
        elif event.estado == "BORRADOR":
            color = 'grey'
        else:
            color = 'rgb(153, 204, 255)'  
        fecha_desde = event.fecha.strftime("%Y-%m-%d")+event.desde.strftime("T%H:%M:%S")
        fecha_hasta = event.fecha.strftime("%Y-%m-%d")+event.hasta.strftime("T%H:%M:%S")                                                                                       
        out.append({                                                                                                    
            'title': event.comentario,                                                                                         
            'id': event.id,                                                                                              
            'start': fecha_desde,                                                         
            'end': fecha_hasta,
            'backgroundColor': color,
            'borderColor': color, 
            'textColor': 'white'
            })  

                                                          
    
    return JsonResponse(out, safe=False)

apps/citas/templates/agendar_cita.html
{% extends 'base.html' %}
{% load static %}

{%block css_page%}
<link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/plugins/forms/pickers/form-flat-pickr.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/plugins/forms/pickers/form-pickadate.css' %}">
<link href="{%static 'plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' %}" rel="stylesheet">
<!-- Page plugins css -->
<link href="{%static 'plugins/clockpicker/dist/jquery-clockpicker.min.css' %}" rel="stylesheet">
<!-- Color picker plugins css -->
<link href="{%static 'plugins/jquery-asColorPicker-master/css/asColorPicker.css' %}" rel="stylesheet">
<!-- Date picker plugins css -->
<link href="{%static 'plugins/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet">
<!-- Daterange picker plugins css -->
<link href="{%static 'plugins/timepicker/bootstrap-timepicker.min.css' %}" rel="stylesheet">
<link href="{%static 'plugins/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
{%endblock%}
{% block content-body %}




<div class="content-body">
    {{error}}
    <div class="row page-titles mx-0">
        <div class="col p-md-0">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
            </ol>
        </div>
    </div>
    <!-- row -->

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="form-validation">
                            <form class="form-valide" action="" method="POST"> {% csrf_token %}
                                <h1>Agendar Cita</h1>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label" for="val-username">Fecha: <span class="text-danger">*</span>
                                    </label>
                                    <div class="col-lg-6">
                                        {{ form.fecha }}
                                    </div>
                                </div>                                
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label" for="val-email">Desde: <span class="text-danger">*</span>
                                    </label>
                                    <div class="col-lg-6">
                                        {{ form.desde }}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label" for="val-email">Hasta: <span class="text-danger">*</span>
                                    </label>
                                    <div class="col-lg-6">
                                        {{ form.hasta }}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label"  for="val-email">Motivo Consulta<span class="text-danger">*</span>
                                    </label>
                                    <div class="col-lg-6">
                                        {{ form.comentario }}
                                    </div>
                                </div>
                                {% if estado_boton == 'BORRADOR' %}
                                <div class="form-group row">
                                    <div class="col-lg-8 ml-auto">
                                        <button type="submit" class="btn btn-primary" id="btn_confirmar_agenda" name="btn_confirmar_agenda">Confirmar</button>
                                    </div>
                                </div>
                                {% endif %}
                                {% if estado_boton == 'CONFIRMADO' %}
                                <div class="form-group row">
                                    <div class="col-lg-8 ml-auto">
                                        <button type="submit" class="btn btn-primary" id="btn_atender_agenda" name="btn_atender_agenda">Atendido</button>
                                        <button type="submit" class="btn btn-primary" id="btn_cancelar_agenda" name="btn_cancelar_agenda">Cancelar</button>
                                    </div>
                                </div>
                                {% endif %}

                                {% if estado_boton == None %}
                                <div class="form-group row">
                                    <div class="col-lg-8 ml-auto">
                                        <button type="submit" class="btn btn-primary" id="btn_agregar_agenda" name="btn_agregar_agenda">Crear</button>
                                    </div>
                                </div>
                                {% endif %}


                                
                            </form>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #/ container -->

</div>



{% endblock %}

{%block js_page%}
<script src="{% static 'plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' %}"></script>
    <!-- Clock Plugin JavaScript -->
<script src="{% static 'plugins/clockpicker/dist/jquery-clockpicker.min.js' %}"></script>
<!-- Color Picker Plugin JavaScript -->
<script src="{% static 'plugins/jquery-asColorPicker-master/libs/jquery-asColor.js' %}"></script>
<script src="{% static 'plugins/jquery-asColorPicker-master/libs/jquery-asGradient.js' %}"></script>
<script src="{% static 'plugins/jquery-asColorPicker-master/dist/jquery-asColorPicker.min.js' %}"></script>
<!-- Date Picker Plugin JavaScript -->
<script src="{% static 'plugins/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
<!-- Date range Plugin JavaScript -->
<script src="{% static 'plugins/timepicker/bootstrap-timepicker.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

<script src="{% static 'js/plugins-init/form-pickers-init.js' %}"></script>
<script src="{% static './plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'app-assets/vendors/js/pickers/flatpickr/flatpickr.min.js' %}"></script>
<script src="{% static 'app-assets/js/scripts/forms/pickers/form-pickers.js' %}"></script>

<script>
    const fechaInicio = document.querySelector('#id_desde');
    
    console.log(fechaInicio)
    recuperarTexto();
    function recuperarTexto() {
        fechaInicio.addEventListener('input', texto);
    }
    function texto() {
        fechaI = fechaInicio.value;
        var timeParts = fechaI.split(":");
        var numberOfMlSeconds = (+timeParts[0] * (60000 * 60)) + (+timeParts[1] * 60000);
        var addMlSeconds = 60 * 30000;
        var fechaFin = (numberOfMlSeconds + addMlSeconds);
        console.log(fechaInicio)
        document.querySelector('#id_hasta').value = msToTime(fechaFin);
        
        
    }
   

    function msToTime(duration) {
        var minutes = Math.floor((duration / (1000 * 60)) % 60),
            hours = Math.floor((duration / (1000 * 60 * 60)) % 24);

        hours = (hours < 10) ? "0" + hours : hours;
        minutes = (minutes < 10) ? "0" + minutes : minutes;
        console.log(hours + ":" + minutes)
        return hours + ":" + minutes;
        }
</script>
{%endblock%}

apps/citas/templates/calendario.html
{% extends 'base.html' %}
{% load static %}


{%block css_page%}
<link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/calendars/fullcalendar.min.css' %}" >
<link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/app-calendar.css' %}" >


{%endblock%}
        
{% block content-body %}
<div class="content-body">

    <section>
        <div class="container-fluid">
            
            <div class="app-calendar overflow-hidden border">
                <div class="row g-0">
                    <!-- Sidebar -->
                    
                    <!-- /Sidebar -->
        
                    <!-- Calendar -->
                    <div class="col position-relative">
                        <div class="card shadow-none border-0 mb-0 rounded-0">
                            <div class="card-body pb-0">
                                <div id="calendar"></div>
                            </div>
                        </div>
                    </div>
                    <!-- /Calendar -->
                    <div class="body-content-overlay"></div>
                </div>
            </div>
            <!-- Calendar Add/Update/Delete event modal-->
            <div class="modal modal-slide-in event-sidebar fade" id="add-new-sidebar">
                <div class="modal-dialog sidebar-lg">
                    <div class="modal-content p-0">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">×</button>
                        <div class="modal-header mb-1">
                            <h5 class="modal-title">Add Event</h5>
                        </div>
                        <div class="modal-body flex-grow-1 pb-sm-0 pb-3">
                            <form class="event-form needs-validation" data-ajax="false" novalidate>
                                <div class="mb-1">
                                    <label for="title" class="form-label">Title</label>
                                    <input type="text" class="form-control" id="title" name="title" placeholder="Event Title" required />
                                </div>
                                <div class="mb-1">
                                    <label for="select-label" class="form-label">Label</label>
                                    <select class="select2 select-label form-select w-100" id="select-label" name="select-label">
                                        <option data-label="primary" value="Business" selected>Business</option>
                                        <option data-label="danger" value="Personal">Personal</option>
                                        <option data-label="warning" value="Family">Family</option>
                                        <option data-label="success" value="Holiday">Holiday</option>
                                        <option data-label="info" value="ETC">ETC</option>
                                    </select>
                                </div>
                                <div class="mb-1 position-relative">
                                    <label for="start-date" class="form-label">Start Date</label>
                                    <input type="text" class="form-control" id="start-date" name="start-date" placeholder="Start Date" />
                                </div>
                                <div class="mb-1 position-relative">
                                    <label for="end-date" class="form-label">End Date</label>
                                    <input type="text" class="form-control" id="end-date" name="end-date" placeholder="End Date" />
                                </div>
                                <div class="mb-1">
                                    <div class="form-check form-switch">
                                        <input type="checkbox" class="form-check-input allDay-switch" id="customSwitch3" />
                                        <label class="form-check-label" for="customSwitch3">All Day</label>
                                    </div>
                                </div>
                                <div class="mb-1">
                                    <label for="event-url" class="form-label">Event URL</label>
                                    
                                </div>
                                <div class="mb-1 select2-primary">
                                    <label for="event-guests" class="form-label">Add Guests</label>
                                    <select class="select2 select-add-guests form-select w-100" id="event-guests" multiple>
                                        <option data-avatar="1-small.png" value="Jane Foster">Jane Foster</option>
                                        <option data-avatar="3-small.png" value="Donna Frank">Donna Frank</option>
                                        <option data-avatar="5-small.png" value="Gabrielle Robertson">Gabrielle Robertson</option>
                                        <option data-avatar="7-small.png" value="Lori Spears">Lori Spears</option>
                                        <option data-avatar="9-small.png" value="Sandy Vega">Sandy Vega</option>
                                        <option data-avatar="11-small.png" value="Cheryl May">Cheryl May</option>
                                    </select>
                                </div>
                                <div class="mb-1">
                                    <label for="event-location" class="form-label">Location</label>
                                    <input type="text" class="form-control" id="event-location" placeholder="Enter Location" />
                                </div>
                                <div class="mb-1">
                                    <label class="form-label">Description</label>
                                    <textarea name="event-description-editor" id="event-description-editor" class="form-control"></textarea>
                                </div>
                                <div class="mb-1 d-flex">
                                    <button type="submit" class="btn btn-primary add-event-btn me-1">Add</button>
                                    <button type="button" class="btn btn-outline-secondary btn-cancel" data-bs-dismiss="modal">Cancel</button>
                                    <button type="submit" class="btn btn-primary update-event-btn d-none me-1">Update</button>
                                    <button class="btn btn-outline-danger btn-delete-event d-none">Delete</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ Calendar Add/Update/Delete event modal-->
    </section>
    <!-- #/ container -->
</div>
{% endblock %}     
        <!--**********************************
            Content body end
        ***********************************-->
        
        
 
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
{%block js_page%}

    
    <script src="{% static 'plugins/jqueryui/js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/calendar/fullcalendar.min.js' %}" ></script>
    <script src="{% static 'app-assets/vendors/js/extensions/moment.min.js' %}" ></script>
    <script src="{% static 'js/plugins-init/fullcalendar-init.js' %}"></script>
    

    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth', selectable: true,
                eventDisplay: 'block', 
                events: '/citas/all_events/',
                eventClick: function(info) {
                    if (info.event.id) {
                        window.open('/citas/editar/' + info.event.id + '/'); 
                        info.jsEvent.preventDefault(); 
                    }           
                },
                select: function(){
                    
                    window.open('/citas/agregar/'); 
                           
                },
            });
            
            calendar.render();
        });

        const calendario = document.querySelector('#calendar');
        calendario.addEventListener('click', (e) => {
            console.log(e.target)

        });

    </script>
{% endblock %}