apps/access/urls.py
from django.urls import path, re_path
from .views import home_view, mision_view, EmpresaUpdateView, ContactoUpdateView
from django.contrib.auth.decorators import login_required

app_name = 'access'

urlpatterns = [
    path('',home_view,name = 'home'),
    path('mision/', mision_view, name = 'mision'),
    path(
        'editar/empresa/<pk>/', 
        login_required(EmpresaUpdateView.as_view()),
        name='editar_empresa'
    ),
    path(
        'editar/contacto/<pk>/', 
        login_required(ContactoUpdateView.as_view()),
        name='editar_contacto'
    ),
]

apps/citas/urls.py
from django.urls import path, re_path
from .views import citas_agregar_views, agendar_create_view1, citas_list_view, all_events, CalendarioListView, CitaCreateView
from django.contrib.auth.decorators import login_required

app_name = 'citas'

urlpatterns = [
    path(
        'agregar/', 
        login_required(agendar_create_view1),
        name = 'agregar_citas'
    ),
    path(
        'editar/<int:id>/', 
        login_required(agendar_create_view1),
        name='confirmar_cita'
    ),
    path(
        'listar/', 
        login_required(citas_list_view),
        name='listar_cita'
    ),
    path(
        'calendario/', 
        login_required(CalendarioListView.as_view()),
        name='calendario'
    ),
    re_path('^all_events', all_events, name='all_events'),
]

apps/cliente/urls.py
from django.urls import path, re_path
from .views import VerPerfilUsuario, signup, login_view, logout_view, ClienteUpdateView
from django.contrib.auth.decorators import login_required

app_name = 'cliente'

urlpatterns = [
    path(
        'signup/', 
        signup,
        name='signup'
    ),
    path(
        '', 
        login_view,
        name='login'
    ),
    path(
        'logout/', 
        logout_view,
        name='logout'
    ),
    path(
        'ver/<pk>/', 
        login_required(VerPerfilUsuario.as_view()),
        name='ver_cliente'
    ),
    path(
        'editar/<pk>/', 
        login_required(ClienteUpdateView.as_view()),
        name='editar_cliente'
    ),
    
]

apps/medico/urls.py
from django.urls import path, re_path
from .views import (
    historial_list_view, export_recetario_medico,
    atencion_view, InsumosCreateView, InsumosListView, 
    CalendarioMedicoListView, all_events1, UsuarioListView, 
    CitasMedicoListView, ProveedorCreateView, crear_insumo
    )
from django.contrib.auth.decorators import login_required


app_name = 'medico'

urlpatterns = [
    path(
        'registrar/proveedor/', 
        login_required(ProveedorCreateView.as_view()),
        name='registrar_proveedor'
    ),
    path(
        'crear/insumos/', 
        login_required(crear_insumo),
        name='crear_insumos'
    ),
    path(
        'listar/insumos/', 
        login_required(InsumosListView.as_view()),
        name='listar_insumos'
    ),
    path(
        'calendario/', 
        login_required(CalendarioMedicoListView.as_view()),
        name='calendario_medico'
    ),
    path(
        'clientes/', 
        login_required(UsuarioListView.as_view()),
        name='clientes_medico'
    ),
    path(
        'citas_cliente/<id>/', 
        login_required(CitasMedicoListView.as_view()),
        name='citas_cliente_medico'
    ),
    path(
        'atencion_cliente/<id>/', 
        login_required(atencion_view),
        name='crear_atencion'
    ),
    path(
        'list_historial/<id>/', 
        login_required(historial_list_view),
        name='list_historial'
    ),
    path('print/recetario/<int:id>/<int:atencion>/', export_recetario_medico, name='print_recetario'),
    re_path('^all_events', all_events1, name='all_events'),
]

clinica/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path, re_path


urlpatterns = [
    path('', include('apps.access.urls')),
    path('admin/', admin.site.urls),
    path('citas/', include('apps.citas.urls')),
    path('medico/', include('apps.medico.urls')),
    path('login/', include('apps.cliente.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Quixlab - Bootstrap Admin Dashboard Template by Themefisher.com</title>
    <!-- Favicon icon -->
    <link rel="icon" type="{% static 'image/png' %}" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <!-- Pignose Calender -->
    <link href="{% static 'plugins/pg-calendar/css/pignose.calendar.min.css' %}" rel="stylesheet">
    <!-- Chartist -->
    <link rel="stylesheet" href="{% static 'plugins/chartist/css/chartist.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css' %}">
    <!-- Custom Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {%block css_page%}
    {%endblock%}
</head>

<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        {% include 'nav_header.html' %}
        <!--**********************************
            Nav header end
        ***********************************-->

        <!--**********************************
            Header start
        ***********************************-->
        {% include 'header.html' %}
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        {% include 'sidebar.html' %}
        <!--**********************************
            Sidebar end
        ***********************************-->

        <!--**********************************
            Content body start
        ***********************************-->
        {% block content-body %}
        {% endblock %}
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        {% include 'footer.html' %}
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    <script src="{% static 'plugins/common/common.min.js' %}"></script>
    <script src="{% static 'js/custom.min.js' %}"></script>
    <script src="{% static 'js/settings.js' %}"></script>
    <script src="{% static 'js/gleek.js' %}"></script>
    <script src="{% static 'js/styleSwitcher.js' %}"></script>

    <!-- Chartjs -->
    <script src="{% static './plugins/chart.js/Chart.bundle.min.js' %}"></script>
    <!-- Circle progress -->
    <script src="{% static './plugins/circle-progress/circle-progress.min.js' %}"></script>
    <!-- Datamap -->
    <script src="{% static './plugins/d3v3/index.js' %}"></script>
    <script src="{% static './plugins/topojson/topojson.min.js' %}"></script>
    <script src="{% static './plugins/datamaps/datamaps.world.min.js' %}"></script>
    <!-- Morrisjs -->
    <script src="{% static './plugins/raphael/raphael.min.js' %}"></script>
    <script src="{% static './plugins/morris/morris.min.js' %}"></script>
    <!-- Pignose Calender -->
    <script src="{% static './plugins/moment/moment.min.js' %}"></script>
    <script src="{% static './plugins/pg-calendar/js/pignose.calendar.min.js' %}"></script>
    <!-- ChartistJS -->
    <script src="{% static './plugins/chartist/js/chartist.min.js' %}"></script>
    <script src="{% static './plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js' %}"></script>



    <script src="{% static './js/dashboard/dashboard-1.js' %}"></script>

    {%block js_page%}

    {%endblock%}
  

</body>

</html>

templates/footer.html
{% load static %}
<div class="footer">
    <div class="copyright">
        <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
    </div>
</div>

templates/header.html
{% load static %}

<div class="header">
    <div class="header-content clearfix">

        <div class="nav-control">
            <div class="hamburger">
                <span class="toggle-icon"><i class="icon-menu"></i></span>
            </div>
        </div>
        <div class="header-left">
            <div class="input-group icons">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-transparent border-0 pr-2 pr-sm-3" id="basic-addon1"><i
                            class="mdi mdi-magnify"></i></span>
                </div>
                <input type="search" class="form-control" placeholder="Search Dashboard" aria-label="Search Dashboard">
                <div class="drop-down animated flipInX d-md-none">
                    <form action="#">
                        <input type="text" class="form-control" placeholder="Search">
                    </form>
                </div>
            </div>
        </div>
        <div class="header-right">
            <ul class="clearfix">
                <li class="icons dropdown"><a href="javascript:void(0)" data-toggle="dropdown">
                        <i class="mdi mdi-email-outline"></i>
                        <span class="badge badge-pill gradient-1">3</span>
                    </a>
                    <div class="drop-down animated fadeIn dropdown-menu">
                        <div class="dropdown-content-heading d-flex justify-content-between">
                            <span class="">3 New Messages</span>
                            <a href="javascript:void()" class="d-inline-block">
                                <span class="badge badge-pill gradient-1">3</span>
                            </a>
                        </div>
                        <div class="dropdown-content-body">
                            <ul>
                                <li class="notification-unread">
                                    <a href="javascript:void()">
                                        <img class="float-left mr-3 avatar-img" src="{% static 'images/avatar/1.jpg' %}" alt="">
                                        <div class="notification-content">
                                            <div class="notification-heading">Saiful Islam</div>
                                            <div class="notification-timestamp">08 Hours ago</div>
                                            <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                                        </div>
                                    </a>
                                </li>
                                <li class="notification-unread">
                                    <a href="javascript:void()">
                                        <img class="float-left mr-3 avatar-img" src="{% static 'images/avatar/2.jpg' %}" alt="">
                                        <div class="notification-content">
                                            <div class="notification-heading">Adam Smith</div>
                                            <div class="notification-timestamp">08 Hours ago</div>
                                            <div class="notification-text">Can you do me a favour?</div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void()">
                                        <img class="float-left mr-3 avatar-img" src="{% static 'images/avatar/3.jpg' %}" alt="">
                                        <div class="notification-content">
                                            <div class="notification-heading">Barak Obama</div>
                                            <div class="notification-timestamp">08 Hours ago</div>
                                            <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void()">
                                        <img class="float-left mr-3 avatar-img" src="{% static 'images/avatar/4.jpg' %}" alt="">
                                        <div class="notification-content">
                                            <div class="notification-heading">Hilari Clinton</div>
                                            <div class="notification-timestamp">08 Hours ago</div>
                                            <div class="notification-text">Hello</div>
                                        </div>
                                    </a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </li>
                <li class="icons dropdown"><a href="javascript:void(0)" data-toggle="dropdown">
                        <i class="mdi mdi-bell-outline"></i>
                        <span class="badge badge-pill gradient-2">3</span>
                    </a>
                    <div class="drop-down animated fadeIn dropdown-menu dropdown-notfication">
                        <div class="dropdown-content-heading d-flex justify-content-between">
                            <span class="">2 New Notifications</span>
                            <a href="javascript:void()" class="d-inline-block">
                                <span class="badge badge-pill gradient-2">5</span>
                            </a>
                        </div>
                        <div class="dropdown-content-body">
                            <ul>
                                <li>
                                    <a href="javascript:void()">
                                        <span class="mr-3 avatar-icon bg-success-lighten-2"><i
                                                class="icon-present"></i></span>
                                        <div class="notification-content">
                                            <h6 class="notification-heading">Events near you</h6>
                                            <span class="notification-text">Within next 5 days</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void()">
                                        <span class="mr-3 avatar-icon bg-danger-lighten-2"><i
                                                class="icon-present"></i></span>
                                        <div class="notification-content">
                                            <h6 class="notification-heading">Event Started</h6>
                                            <span class="notification-text">One hour ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void()">
                                        <span class="mr-3 avatar-icon bg-success-lighten-2"><i
                                                class="icon-present"></i></span>
                                        <div class="notification-content">
                                            <h6 class="notification-heading">Event Ended Successfully</h6>
                                            <span class="notification-text">One hour ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void()">
                                        <span class="mr-3 avatar-icon bg-danger-lighten-2"><i
                                                class="icon-present"></i></span>
                                        <div class="notification-content">
                                            <h6 class="notification-heading">Events to Join</h6>
                                            <span class="notification-text">After two days</span>
                                        </div>
                                    </a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </li>
                <li class="icons dropdown d-none d-md-flex">
                    <a href="javascript:void(0)" class="log-user" data-toggle="dropdown">
                        <span>English</span> <i class="fa fa-angle-down f-s-14" aria-hidden="true"></i>
                    </a>
                    <div class="drop-down dropdown-language animated fadeIn  dropdown-menu">
                        <div class="dropdown-content-body">
                            <ul>
                                <li><a href="javascript:void()">English</a></li>
                                <li><a href="javascript:void()">Dutch</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="icons dropdown">
                    <div class="user-img c-pointer position-relative" data-toggle="dropdown">
                        <span class="activity active"></span>
                        <img src="images/user/1.png" height="40" width="40" alt="">
                    </div>
                    <div class="drop-down dropdown-profile animated fadeIn dropdown-menu">
                        <div class="dropdown-content-body">
                            <ul>
                                <li>
                                    <a href="app-profile.html"><i class="icon-user"></i> <span>Profile</span></a>
                                </li>
                                <li>
                                    <a href="javascript:void()">
                                        <i class="icon-envelope-open"></i> <span>Inbox</span>
                                        <div class="badge gradient-3 badge-pill gradient-1">3</div>
                                    </a>
                                </li>

                                <hr class="my-2">
                                <li>
                                    <a href="page-lock.html"><i class="icon-lock"></i> <span>Lock Screen</span></a>
                                </li>
                                <li><a href="{% url 'cliente:logout' %}"><i class="icon-key"></i> <span>Logout</span></a></li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/nav_header.html
{% load static %}

<div class="nav-header">
    <div class="brand-logo">
        <a href="index.html">
            <b class="logo-abbr"><img src="{% static 'images/logo.png' %}" alt=""> </b>
            <span class="logo-compact"><img src="{% static 'images/logo-compact.png' %}" alt=""></span>
            <span class="brand-title">
                <img src="{% static 'images/logo-text.png' %}" alt="">
            </span>
        </a>
    </div>
</div>

templates/sidebar.html
{% load static %}
<div class="nk-sidebar">           
    <div class="nk-nav-scroll">
        <ul class="metismenu" id="menu">
            <li class="nav-label">Dashboard</li>
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-user menu-icon"></i><span class="nav-text">Usuario</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'cliente:ver_cliente' request.user.id %}">Perfil</a></li>
                </ul>
                
            </li>
            {% if perms.cliente.ver_cliente %}
            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-globe-alt menu-icon"></i><span class="nav-text">Citas</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'citas:agregar_citas' %}">Agendar</a></li>
                    <li><a href="{% url 'citas:listar_cita' %}">Listado</a></li>
                    <li><a href="{% url 'citas:calendario' %}">Calendario</a></li>
                </ul>
            </li>
            {% endif %}
            {% if perms.medico.ver_medico %}
            <li class="nav-label">Medico</li>
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-envelope menu-icon"></i> <span class="nav-text">Inventario</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'medico:crear_insumos' %}">Agregar</a></li>
                    <li><a href="{% url 'medico:listar_insumos' %}">Listado</a></li>
                </ul>
            </li>

            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-globe-alt menu-icon"></i><span class="nav-text">Clientes</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'medico:clientes_medico' %}">listado</a></li>
                    <li><a href="{% url 'medico:calendario_medico' %}">Calendario</a></li>
                </ul>
            </li>

            
            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-globe-alt menu-icon"></i><span class="nav-text">Compra</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'medico:registrar_proveedor' %}">Proveedor</a></li>
                    <li><a href="{% url 'medico:crear_insumos' %}">Producto</a></li>
                </ul>
            </li>

            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Portada</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'access:editar_empresa' 1 %}">Editar Empresa</a></li>
                    <li><a href="{% url 'access:editar_contacto' 1 %}">Editar Contacto</a></li>
                </ul>
            </li>
            {% endif %}
            
            {% comment %}
            <li class="nav-label">UI Components</li>
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-grid menu-icon"></i><span class="nav-text">UI Components</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="./ui-accordion.html">Accordion</a></li>
                    <li><a href="./ui-alert.html">Alert</a></li>
                    <li><a href="./ui-badge.html">Badge</a></li>
                    <li><a href="./ui-button.html">Button</a></li>
                    <li><a href="./ui-button-group.html">Button Group</a></li>
                    <li><a href="./ui-cards.html">Cards</a></li>
                    <li><a href="./ui-carousel.html">Carousel</a></li>
                    <li><a href="./ui-dropdown.html">Dropdown</a></li>
                    <li><a href="./ui-list-group.html">List Group</a></li>
                    <li><a href="./ui-media-object.html">Media Object</a></li>
                    <li><a href="./ui-modal.html">Modal</a></li>
                    <li><a href="./ui-pagination.html">Pagination</a></li>
                    <li><a href="./ui-popover.html">Popover</a></li>
                    <li><a href="./ui-progressbar.html">Progressbar</a></li>
                    <li><a href="./ui-tab.html">Tab</a></li>
                    <li><a href="./ui-typography.html">Typography</a></li>
                <!-- </ul>
            </li>
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-layers menu-icon"></i><span class="nav-text">Components</span>
                </a>
                <ul aria-expanded="false"> -->
                    <li><a href="./uc-nestedable.html">Nestedable</a></li>
                    <li><a href="./uc-noui-slider.html">Noui Slider</a></li>
                    <li><a href="./uc-sweetalert.html">Sweet Alert</a></li>
                    <li><a href="./uc-toastr.html">Toastr</a></li>
                </ul>
            </li>
            <li>
                <a href="widgets.html" aria-expanded="false">
                    <i class="icon-badge menu-icon"></i><span class="nav-text">Widget</span>
                </a>
            </li>
            <li class="nav-label">Forms</li>
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-note menu-icon"></i><span class="nav-text">Forms</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="./form-basic.html">Basic Form</a></li>
                    <li><a href="./form-validation.html">Form Validation</a></li>
                    <li><a href="./form-step.html">Step Form</a></li>
                    <li><a href="./form-editor.html">Editor</a></li>
                    <li><a href="./form-picker.html">Picker</a></li>
                </ul>
            </li>
            <li class="nav-label">Table</li>
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-menu menu-icon"></i><span class="nav-text">Table</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="./table-basic.html" aria-expanded="false">Basic Table</a></li>
                    <li><a href="./table-datatable.html" aria-expanded="false">Data Table</a></li>
                </ul>
            </li>
            <li class="nav-label">Pages</li>
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-notebook menu-icon"></i><span class="nav-text">Pages</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="./page-login.html">Login</a></li>
                    <li><a href="./page-register.html">Register</a></li>
                    <li><a href="./page-lock.html">Lock Screen</a></li>
                    <li><a class="has-arrow" href="javascript:void()" aria-expanded="false">Error</a>
                        <ul aria-expanded="false">
                            <li><a href="./page-error-404.html">Error 404</a></li>
                            <li><a href="./page-error-403.html">Error 403</a></li>
                            <li><a href="./page-error-400.html">Error 400</a></li>
                            <li><a href="./page-error-500.html">Error 500</a></li>
                            <li><a href="./page-error-503.html">Error 503</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            {% endcomment %}
        </ul>
    </div>
</div>