apps/cliente/urls.py
from django.urls import path, re_path
from .views import VerPerfilUsuario, signup, login_view, logout_view, ClienteUpdateView
from django.contrib.auth.decorators import login_required

app_name = 'cliente'

urlpatterns = [
    path(
        'signup/', 
        signup,
        name='signup'
    ),
    path(
        '', 
        login_view,
        name='login'
    ),
    path(
        'logout/', 
        logout_view,
        name='logout'
    ),
    path(
        'ver/<pk>/', 
        login_required(VerPerfilUsuario.as_view()),
        name='ver_cliente'
    ),
    path(
        'editar/<pk>/', 
        login_required(ClienteUpdateView.as_view()),
        name='editar_cliente'
    ),
    
]

apps/medico/urls.py
from django.urls import path, re_path
from .views import (
    historial_list_view, export_recetario_medico,
    atencion_view, InsumosCreateView, InsumosListView, 
    CalendarioMedicoListView, all_events1, UsuarioListView, 
    CitasMedicoListView, ProveedorCreateView, crear_insumo
    )
from django.contrib.auth.decorators import login_required


app_name = 'medico'

urlpatterns = [
    path(
        'registrar/proveedor/', 
        login_required(ProveedorCreateView.as_view()),
        name='registrar_proveedor'
    ),
    path(
        'crear/insumos/', 
        login_required(crear_insumo),
        name='crear_insumos'
    ),
    path(
        'listar/insumos/', 
        login_required(InsumosListView.as_view()),
        name='listar_insumos'
    ),
    path(
        'calendario/', 
        login_required(CalendarioMedicoListView.as_view()),
        name='calendario_medico'
    ),
    path(
        'clientes/', 
        login_required(UsuarioListView.as_view()),
        name='clientes_medico'
    ),
    path(
        'citas_cliente/<id>/', 
        login_required(CitasMedicoListView.as_view()),
        name='citas_cliente_medico'
    ),
    path(
        'atencion_cliente/<id>/', 
        login_required(atencion_view),
        name='crear_atencion'
    ),
    path(
        'list_historial/<id>/', 
        login_required(historial_list_view),
        name='list_historial'
    ),
    path('print/recetario/<int:id>/<int:atencion>/', export_recetario_medico, name='print_recetario'),
    re_path('^all_events', all_events1, name='all_events'),
]

clinica/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path, re_path


urlpatterns = [
    path('', include('apps.access.urls')),
    path('admin/', admin.site.urls),
    path('citas/', include('apps.citas.urls')),
    path('medico/', include('apps.medico.urls')),
    path('login/', include('apps.cliente.urls')),
]

apps/cliente/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Usuario(models.Model):
    opciones_genero = (
        ('Masculino', 'Masculino'),
        ('Femenino', 'Femenino'),
        ('N/A', 'N/A'),
    )
    tipos_sangre = (
        ('A+','A+'),
        ('A-','A-'),
        ('B+','B+'),
        ('B-','B-'),
        ('AB+','AB+'),
        ('AB-','AB-'),
        ('O+','O+'),
        ('O-','O-'),
    )
    identificacion = models.CharField('Cedula', max_length=15, blank=False, null=False)
    nombres = models.CharField('Nombre', max_length=100, blank=False, null=False)
    apellidos = models.CharField('Apellido', max_length=100, blank=False, null=False)
    lugar_nacimiento = models.CharField('LugarN', max_length=50, blank=False, null=False)
    fecha_nacimiento = models.DateField('FechaN', blank=False, null=False)
    edad = models.IntegerField(blank=False, null=False)
    direccion = models.CharField('Direccion', max_length=300,  blank=False, null=False)
    canton = models.CharField('Canton', max_length=50, blank=False, null=False)
    provincia = models.CharField('Provincia', max_length=50, blank=False, null=False)
    pais = models.CharField('Pais', max_length=50, blank=False, null=False)
    sexo = models.CharField('Sexo',max_length=20, choices = opciones_genero)
    tipo_sangre = models.CharField('TipoS',max_length=5, choices = tipos_sangre)
    celular = models.CharField('Celular', max_length=15, blank=False, null=False)
    correo = models.EmailField()
    #Contacto emergencia
    nombre_contacto_emergencia = models.CharField('NombreE', max_length=200, blank=True, null=True)
    parentesco_contacto_emergencia = models.CharField('ParentescoE', max_length=80, blank=True, null=True)
    telefono_contacto_emergencia = models.CharField('CelularE', max_length=15, blank=True, null=True)
    #Menor de Edad
    is_menor =  models.BooleanField('Es_menor', default=False)
    nombre_tutor = models.CharField('NombreT', max_length=200, blank=True, null=True)
    parentesco_tutor = models.CharField('ParentescoT', max_length=80, blank=True, null=True)
    telefono_tutor = models.CharField('CelularT', max_length=15, blank=True, null=True)
    direccion_tutor = models.CharField('DireccionT', max_length=300, blank=True, null=True)
    username = models.CharField('Username', max_length=100, blank=False, null=False)
    def __str__(self):
        return self.nombres + ' ' + self.apellidos

    class Meta:
        managed = False
        db_table = 'usuario'


class Historial(models.Model):
    cliente = models.ForeignKey(Usuario, models.DO_NOTHING, db_column='id_cliente')

    class Meta:
        managed = False
        db_table = 'historial'

class Atencion(models.Model):
    m_consulta = models.TextField(blank=True, null=True)
    enf_actual = models.TextField(blank=True, null=True)
    antecedentes = models.TextField(blank=True, null=True)
    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    id_historial = models.ForeignKey('Historial', models.DO_NOTHING, db_column='id_historial', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'atencion'

class Odontograma(models.Model):

    selector = (
        ('11','11'),
        ('12','12'),
        ('13','13'),
        ('14','14'),
        ('15','15'),
        ('16','16'),
        ('17','17'),
        ('18','18'),
        ('21','21'),
        ('22','22'),
        ('23','23'),
        ('24','24'),
        ('25','25'),
        ('26','26'),
        ('27','27'),
        ('28','28'),
        ('31','31'),
        ('32','32'),
        ('33','33'),
        ('34','34'),
        ('35','35'),
        ('36','36'),
        ('37','37'),
        ('38','38'),
        ('41','41'),
        ('42','42'),
        ('43','43'),
        ('44','44'),
        ('45','45'),
        ('46','46'),
        ('47','47'),
        ('48','48'),
        ('51','51'),
        ('52','52'),
        ('53','53'),
        ('54','54'),
        ('55','55'),
        ('61','61'),
        ('62','62'),
        ('63','63'),
        ('64','64'),
        ('65','65'),
        ('71','71'),
        ('72','72'),
        ('73','73'),
        ('74','74'),
        ('75','75'),
        ('81','81'),
        ('82','82'),
        ('83','83'),
        ('84','84'),
        ('85','85'),
    )
    simbologia = (
        ('Sellante necesario','Sellante necesario'),
        ('A-Sellante necesario','A-Sellante necesario'),
        ('Extraccion indicada','Extraccion indicada'),
        ('Perdida por caries','Perdida por caries'),
        ('Perdida(otra causa)','Perdida(otra causa)'),
        ('Endodoncia','Endodoncia'),
        ('Protesis Fija','Protesis Fija'),
        ('Protesis removible','Protesis removible'),
        ('Protesis total','Protesis total'),
        ('Corona','Corona'),
        ('Caries','Caries'),
        ('Obturado','Obturado'),
    )
    id_atencion = models.ForeignKey(Atencion, models.DO_NOTHING, db_column='id_atencion', blank=True, null=True)
    diente = models.CharField('Tipos',max_length=5, choices = selector)
    detalle = models.CharField('Simbologia',max_length=35, choices = simbologia)
    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'odontograma'




class Estomatogmatico(models.Model):

    selector = (
        ('Labios','Labios'),
        ('Glandulas salivales','Glandulas salivales'),
        ('Mejilla','Mejilla'),
        ('Maxilar','Maxilar'),
        ('Mandibula','Mandibula'),
        ('Lengua','Lengua'),
        ('Paladar','Paladar'),
        ('Piso de boca','Piso de boca'),
        ('Orofaringe','Orofaringe'),
        ('Atm','Atm'),
        ('Ganglios','Ganglios'),
        ('Carillos','Carillos'),
    )
    id_atencion = models.ForeignKey(Atencion, models.DO_NOTHING, db_column='id_atencion', blank=True, null=True)
    tipo = models.CharField('Tipos',max_length=45, choices = selector)
    detalle = models.TextField(blank=True, null=True)
    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'estomatogmatico'


class PlanesDiagnostico(models.Model):
    id_atencion = models.ForeignKey(Atencion, models.DO_NOTHING, db_column='id_atencion', blank=True, null=True)
    procedimiento = models.TextField(blank=True, null=True)
    detalles = models.TextField(blank=True, null=True)
    tipo = models.TextField(blank=True, null=True)
    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'planes_diagnostico'


class SaludOral(models.Model):
    id_atencion = models.ForeignKey(Atencion, models.DO_NOTHING, db_column='id_atencion', blank=True, null=True)
    piezas_dentales = models.IntegerField(blank=True, null=True)
    placa = models.IntegerField(blank=True, null=True)
    calculo = models.IntegerField(blank=True, null=True)
    gingivitis = models.IntegerField(blank=True, null=True)
    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'salud_oral'

class SignosVitales(models.Model):
    id_atencion = models.ForeignKey(Atencion, models.DO_NOTHING, db_column='id_atencion', blank=True, null=True)
    presion_arterial = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    frecuencia_cardiaca = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    temperatura = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    frecuencia_respiratoria = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'signos_vitales'

apps/cliente/forms.py
from django import forms

from django.contrib.admin import widgets

from .models import Usuario, Atencion, Historial, Estomatogmatico, SignosVitales, Odontograma, PlanesDiagnostico
from datetime import datetime, date

class UpdateClienteForm(forms.ModelForm):
    
    
    def __init__(self, *args, **kwargs):
        super(UpdateClienteForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-control'
        
        self.fields['fecha_nacimiento'].widget.attrs['class'] = 'form-control mydatepicker'
        
    
    class Meta:
        model = Usuario
        fields = [
            'identificacion',
            'nombres',
            'apellidos',
            'lugar_nacimiento',
            'fecha_nacimiento',
            'edad',
            'direccion',
            'canton',
            'provincia',
            'pais',
            'sexo',
            'tipo_sangre',
            'celular',
            'correo',
            #Contacto emergencia
            'nombre_contacto_emergencia',
            'parentesco_contacto_emergencia',
            'telefono_contacto_emergencia',
            #Menor de Edad
            'is_menor',
            'nombre_tutor',
            'parentesco_tutor',
            'telefono_tutor',
            'direccion_tutor',
        ]
        

apps/cliente/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from .forms import UpdateClienteForm
from .models import Usuario, Historial, Atencion

from .models import Usuario
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
)


class VerPerfilUsuario(DetailView):
    model = Usuario
    template_name = 'ver_usuario.html'
    context_object_name = 'usuario'
    

class ClienteUpdateView(UpdateView):
    model = Usuario
    template_name = 'editar_cliente.html'
    form_class = UpdateClienteForm

    def get_success_url(self):
        usuario_id = self.request.user.id
        return reverse('cliente:ver_cliente', kwargs={'pk': usuario_id})

# Create your views here.
def login_view(request):

    if request.method == 'POST':
        username = request.POST['usuario']
        password = request.POST['passwd']
        user=authenticate(request, username=username, password=password)
        print(user)
        if user:
            
            login(request,user)
            #return reverse('cliente:ver_cliente', request.user.id)
            return redirect('cliente:editar_cliente', request.user.id)
        else:
            return render(request,'login.html',{'error':'Passwords no coinciden'})
    return render(request,'login.html')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        nombre = request.POST['nombre']
        apellido = request.POST['apellido']
        passwd = request.POST['passwd']
        passwd_confirmation = request.POST['passwd_confirmation']
        if passwd != passwd_confirmation:
            print('error')
            return render(request, 'signup.html', {'error':'Passwords no coinciden'} )
        if Usuario.objects.filter(username=username).exists():
            return render(request, 'signup.html', {'error1':'Nombre de usuario ya registrado'} )

        user = User.objects.create(
            username=username,
            password=make_password(passwd),
            first_name=nombre,
            last_name=apellido,
            )
        
        perfil = Usuario(
            id=user.id,
            username=username,
            nombres=nombre,
            apellidos=apellido
            )
        perfil.save()
        historial = Historial.objects.create(
            cliente = Usuario.objects.get(username=username)
        )
        
        historial.save()
        return redirect('cliente:login')
    return render(request, 'signup.html')
    
@login_required
def logout_view(request):
    logout(request)
    return redirect('access:home')

apps/cliente/templates/login.html
{% load static %}

<html class="h-100" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Quixlab - Bootstrap Admin Dashboard Template by Themefisher.com</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <!-- Pignose Calender -->
    <link href="{% static 'plugins/pg-calendar/css/pignose.calendar.min.css' %}" rel="stylesheet">
    <!-- Chartist -->
    <link rel="stylesheet" href="{% static 'plugins/chartist/css/chartist.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css' %}">
    <!-- Custom Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {%block css_page%}
    {%endblock%}
</head>

<body class="h-100">
    
    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    



    <div class="login-form-bg h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100">
                <div class="col-xl-6">
                    <div class="form-input-content">
                        <div class="card login-form mb-0">
                            <div class="card-body pt-5">
                                <a class="text-center" href="index.html"> <h4>Rosella</h4></a>
        
                                <form class="mt-5 mb-5 login-input" action="{% url 'cliente:login' %}" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Usuario" name="usuario">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" placeholder="Password" name="passwd">
                                    </div>
                                    <button class="btn login-form__btn submit w-100" type="submit">Sign In</button>
                                </form>
                                <p class="mt-5 login-form__footer">Dont have account? <a href="{% url 'cliente:signup'%}" class="text-primary">Sign Up</a> now</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    

    <!--**********************************
        Scripts
    ***********************************-->
    
    <script src="{% static 'plugins/common/common.min.js' %}"></script>
    <script src="{% static 'js/custom.min.js' %}"></script>
    <script src="{% static 'js/settings.js' %}"></script>
    <script src="{% static 'js/gleek.js' %}"></script>
    <script src="{% static 'js/styleSwitcher.js' %}"></script>
</body>
</html>

apps/cliente/templates/signup.html
{% load static %}

<html class="h-100" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Quixlab - Bootstrap Admin Dashboard Template by Themefisher.com</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <!-- Pignose Calender -->
    <link href="{% static 'plugins/pg-calendar/css/pignose.calendar.min.css' %}" rel="stylesheet">
    <!-- Chartist -->
    <link rel="stylesheet" href="{% static 'plugins/chartist/css/chartist.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css' %}">
    <!-- Custom Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {%block css_page%}
    {%endblock%}
</head>

<body class="h-100">
    
    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    



    <div class="login-form-bg h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100">
                <div class="col-xl-6">
                    <div class="form-input-content">
                        <div class="card login-form mb-0">
                            <div class="card-body pt-5">
                                
                                    <a class="text-center" href="index.html"> <h4>Rosella</h4></a>
        
                                <form class="mt-5 mb-5 login-input" action="{% url 'cliente:signup' %}" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{error1}}
                                        <input type="text" class="form-control"  placeholder="Usuario" name="username" required="true">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control"  placeholder="Nombre" name="nombre" required="true">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control"  placeholder="Apellido" name="apellido" required="true">
                                    </div>
                                    <div class="form-group">
                                        {{error}}
                                        <input type="password" class="form-control" placeholder="Password" name="passwd" required="true">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" placeholder="Confirm Password" name="passwd_confirmation" required="true">
                                    </div>
                                    <button class="btn login-form__btn submit w-100" type="submit">Sign in</button>
                                </form>
                                    <p class="mt-5 login-form__footer">Have account <a href="{% url 'cliente:login'%}" class="text-primary">Sign Up </a> now</p>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

    

    <!--**********************************
        Scripts
    ***********************************-->
    
    <script src="{% static 'plugins/common/common.min.js' %}"></script>
    <script src="{% static 'js/custom.min.js' %}"></script>
    <script src="{% static 'js/settings.js' %}"></script>
    <script src="{% static 'js/gleek.js' %}"></script>
    <script src="{% static 'js/styleSwitcher.js' %}"></script>
</body>
</html>

apps/cliente/templates/ver_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block content-body %}

<div class="content-body">

   
    <!-- row -->

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8 col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <div class="media align-items-center mb-4">
                            
                            <div class="media-body">
                                <center>
                                <h2 class="mb-0">{{usuario.nombres}}  {{usuario.apellidos}}</h2>
                                <p class="text-muted mb-0">{{usuario.identificacion}}</p>
                                </center>
                            </div>
                        </div>
                        
                        <div class="row mb-5">
                            <div class="col">
                                
                                <ul class="card-profile__info">
                                    <li class="mb-1"><strong class="text-dark mr-4">Lugar de nacimiento</strong> <span>{{usuario.lugar_nacimiento}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Fecha de nacimiento</strong> <span>{{usuario.fecha_nacimiento}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Edad</strong> <span>{{usuario.edad}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Direccion</strong> <span>{{usuario.direccion}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Canton</strong> <span>{{usuario.canton}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Provincia</strong> <span>{{usuario.provincia}}</span></li>
                                    
                                </ul>
                                
                            </div>
                            <div class="col">
                                
                                <ul class="card-profile__info">
                                    <li class="mb-1"><strong class="text-dark mr-4">Pais</strong> <span>{{usuario.pais}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Sexo</strong> <span>{{usuario.sexo}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Tipo Sangre</strong> <span>{{usuario.tipo_sangre}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Lugar de nacimiento</strong> <span>{{usuario.pais}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Celular</strong> <span>{{usuario.celular}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Correo</strong> <span>{{usuario.correo}}</span></li>
                                    <li class="mb-1"><strong class="text-dark mr-4">Lugar de nacimiento</strong> <span>{{usuario.pais}}</span></li>
                                </ul>
                                
                            </div>
                            <div class="col-12 text-center">
                                <h4>Contacto de Emergencia</h4>
                            </div>
                            <div class="col-12 ">
                                <li class="mb-1"><strong class="text-dark mr-4">Nombre</strong> <span>{{usuario.nombre_contacto_emergencia}}</span></li>
                                <li class="mb-1"><strong class="text-dark mr-4">Parentesco</strong> <span>{{usuario.parentesco_contacto_emergencia}}</span></li>
                                <li class="mb-1"><strong class="text-dark mr-4">Telefono</strong> <span>{{usuario.telefono_contacto_emergencia}}</span></li>
                            </div>
                            <div class="col-12 text-center">
                                <h4>Tutor Legal</h4>
                            </div>
                            <div class="col-12 ">
                                <li class="mb-1"><strong class="text-dark mr-4">Nombre</strong> <span>{{usuario.nombre_tutor}}</span></li>
                                <li class="mb-1"><strong class="text-dark mr-4">Parentesco</strong> <span>{{usuario.parentesco_tutor}}</span></li>
                                <li class="mb-1"><strong class="text-dark mr-4">Telefono</strong> <span>{{usuario.telefono_tutor}}</span></li>
                                <li class="mb-1"><strong class="text-dark mr-4">Direccion</strong> <span>{{usuario.direccion_tutor}}</span></li>
                            </div>
                        </div>

                        <a href="{% url 'cliente:editar_cliente' usuario.id %}" type="button"  class="btn mb-1 btn-outline-info">Editar</a> 
                        {% if perms.cliente.ver_cliente %}   
                        <a href="{% url 'medico:list_historial' usuario.id %}" type="button"  class="btn mb-1 btn-outline-info">Historial</a>  
                        {% endif %}
                    </div>
                </div>  
            </div>
            
        </div>
        
    </div>
{% endblock %}