apps/medico/urls.py
from django.urls import path, re_path
from .views import (
    historial_list_view, export_recetario_medico,
    atencion_view, InsumosCreateView, InsumosListView, 
    CalendarioMedicoListView, all_events1, UsuarioListView, 
    CitasMedicoListView, ProveedorCreateView, crear_insumo
    )
from django.contrib.auth.decorators import login_required


app_name = 'medico'

urlpatterns = [
    path(
        'registrar/proveedor/', 
        login_required(ProveedorCreateView.as_view()),
        name='registrar_proveedor'
    ),
    path(
        'crear/insumos/', 
        login_required(crear_insumo),
        name='crear_insumos'
    ),
    path(
        'listar/insumos/', 
        login_required(InsumosListView.as_view()),
        name='listar_insumos'
    ),
    path(
        'calendario/', 
        login_required(CalendarioMedicoListView.as_view()),
        name='calendario_medico'
    ),
    path(
        'clientes/', 
        login_required(UsuarioListView.as_view()),
        name='clientes_medico'
    ),
    path(
        'citas_cliente/<id>/', 
        login_required(CitasMedicoListView.as_view()),
        name='citas_cliente_medico'
    ),
    path(
        'atencion_cliente/<id>/', 
        login_required(atencion_view),
        name='crear_atencion'
    ),
    path(
        'list_historial/<id>/', 
        login_required(historial_list_view),
        name='list_historial'
    ),
    path('print/recetario/<int:id>/<int:atencion>/', export_recetario_medico, name='print_recetario'),
    re_path('^all_events', all_events1, name='all_events'),
]

clinica/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path, re_path


urlpatterns = [
    path('', include('apps.access.urls')),
    path('admin/', admin.site.urls),
    path('citas/', include('apps.citas.urls')),
    path('medico/', include('apps.medico.urls')),
    path('login/', include('apps.cliente.urls')),
]

apps/medico/models.py
from django.db import models



# Create your models here.
class Insumos(models.Model):
    id_producto = models.ForeignKey('Producto', models.DO_NOTHING, db_column='id_producto', blank=True, null=True)
    cantidad = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'insumos'



class Proveedor(models.Model):
    identificacion = models.CharField(max_length=20, blank=True, null=True)
    nombre = models.CharField(max_length=50, blank=True, null=True)
    apellido = models.CharField(max_length=50, blank=True, null=True)
    telefono = models.CharField(max_length=13, blank=True, null=True)
    direccion = models.CharField(max_length=200, blank=True, null=True)
    correo = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.nombre+" "+self.apellido
    class Meta:
        managed = False
        db_table = 'proveedor'

class Producto(models.Model):
    nombre = models.CharField(max_length=150, blank=True, null=True)
    precio = models.FloatField(blank=True, null=True)
    cantidad = models.IntegerField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    id_proveedor = models.ForeignKey('Proveedor', models.DO_NOTHING, db_column='id_proveedor')

    
    class Meta:
        managed = False
        db_table = 'producto'

apps/medico/forms.py
from django import forms

from django.contrib.admin import widgets

from apps.cliente.models import Usuario, Atencion, Historial, Estomatogmatico, SignosVitales, Odontograma, PlanesDiagnostico
from .models import Producto
from datetime import datetime, date



class AtencionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AtencionForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Atencion
        fields = [
            'm_consulta', 
            'enf_actual',
            'antecedentes',        
        ]

class EstomatogmaticoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EstomatogmaticoForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Estomatogmatico
        fields = [
            'tipo', 
            'detalle',        
        ]

class SignosForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(SignosForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = SignosVitales
        fields = [
            'presion_arterial', 
            'frecuencia_cardiaca',    
            'temperatura',   
            'frecuencia_respiratoria',
        ]

class OdontogramaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(OdontogramaForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Odontograma
        fields = [
            'diente', 
            'detalle',    
        ]

class ProductoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProductoForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Producto
        fields = [
            'nombre', 
            'precio',  
            'cantidad',
            'id_proveedor'
        ]

apps/medico/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import get_object_or_404, redirect, render
from django.http.response import Http404, HttpResponse
from django.contrib.auth.decorators import permission_required
from django.urls import reverse_lazy, reverse
from .models import Insumos, Proveedor, Producto
from django.db.models import Q
from apps.citas.models import Agenda
from apps.cliente.models import Usuario, Atencion, Historial, Estomatogmatico, SignosVitales, Odontograma
from .forms import AtencionForm, EstomatogmaticoForm, SignosForm, OdontogramaForm, ProductoForm
from .parsers import export_reporte_hoja_calculo
from .constantes import FORMATOS_ARCHIVOS
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
)

from django.http import HttpResponse, JsonResponse
import json

# Create your views here.

class ProveedorCreateView(CreateView):
    model = Proveedor
    template_name = 'registrar_proveedor.html'
    fields = [
        'identificacion', 
        'nombre', 
        'apellido',
        'telefono',
        'direccion',
        'correo'
        ]

    success_url = reverse_lazy('medico:registrar_proveedor')

class InsumosCreateView(CreateView):
    model = Insumos 
    template_name = 'crear_insumo.html'
    fields = ['nombre', 'detalle', 'stock']
    success_url = reverse_lazy('medico:agregar_insumos')

def crear_insumo(request):
    template_name = 'crear_insumo.html'
    producto=ProductoForm(request.POST or None)
    context = {
        'producto':producto
    }
    if request.method == 'POST':
        if producto.is_valid():
            nombre = producto.cleaned_data.get('nombre')
            precio = producto.cleaned_data.get('precio')
            cantidad = producto.cleaned_data.get('cantidad')
            id_proveedor = producto.cleaned_data.get('id_proveedor')
            total = precio*cantidad

            producto_obj = Producto.objects.create(
                nombre = nombre,
                precio = precio,
                cantidad = cantidad,
                total = total,
                id_proveedor = id_proveedor,                        
                )
            try:
                insumo = Insumos.objects.get(id_producto=producto_obj.id)
            except:
                producto_id=Producto.objects.get(id=producto_obj.id)
                Insumos.objects.create(
                    id_producto=producto_id,
                    cantidad=cantidad,
                )
            
            #producto.save()
            
            return redirect('cliente:editar_cliente', request.user.id)



    return render(request, template_name, context)
    

class InsumosListView(ListView):
    model = Insumos
    template_name = 'listar_insumos.html'
    context_object_name = 'insumos'

class UsuarioListView(ListView):
    model = Usuario
    template_name = 'clientes_medico/listar_clientes.html'
    context_object_name = 'clientes'
    paginate_by = 25

class CalendarioMedicoListView(ListView):
    model = Agenda
    template_name = 'cita_medica/calendario.html'
    context_object_name = 'agenda'

def all_events1(request, id = None):  
    
    all_events = Agenda.objects.all() 
                                                                                    
    out = []                                                                                                             
    for event in all_events:  
        if event.estado == "CANCELADA":
            color = 'rgb(255,51,51)'
        elif event.estado == "CONFIRMADO":
            color = 'rgb(136,255,77)'
        elif event.estado == "BORRADOR":
            color = 'grey'
        else:
            color = 'rgb(153, 204, 255)'  
        fecha_desde = event.fecha.strftime("%Y-%m-%d")+event.desde.strftime("T%H:%M:%S")
        fecha_hasta = event.fecha.strftime("%Y-%m-%d")+event.hasta.strftime("T%H:%M:%S")                                                                                       
        out.append({                                                                                                    
            'title': event.comentario,                                                                                         
            'id': event.id,                                                                                              
            'start': fecha_desde,                                                         
            'end': fecha_hasta,
            'backgroundColor': color,
            'borderColor': color, 
            'textColor': 'white'
            })  

                                                          
    
    return JsonResponse(out, safe=False)

class CitasMedicoListView(ListView):
    model = Agenda
    template_name = 'cita_medica/listar_cita.html'
    context_object_name = 'agenda'
    def get_queryset(self):
        id = self.kwargs['id']
        agenda = Agenda.objects.filter(cliente=id)
        return agenda
    
def atencion_view(request,id=None):
    template_name = 'agenda/crear_atencion.html'
    form_atencion = AtencionForm(request.POST or None)
    form_estomatogmatico = EstomatogmaticoForm(request.POST or None)
    form_signos = SignosForm(request.POST or None)
    print(form_signos)
    form_odontograma = OdontogramaForm(request.POST or None)
    usuario = Usuario.objects.get(id=id)
    historial_id = Historial.objects.get(cliente = usuario)
    print(historial_id.id)
    if request.method == 'POST':

        if form_atencion.is_valid():
            print('atencion')
            consulta = form_atencion.cleaned_data.get('m_consulta')
            enfermedad = form_atencion.cleaned_data.get('enf_actual')
            antecedentes = form_atencion.cleaned_data.get('antecedentes')

            atencion = Atencion.objects.create(
                m_consulta = consulta,
                enf_actual = enfermedad,
                antecedentes = antecedentes,
                id_historial = historial_id,
            )            
            atencion.save()
            if form_signos.is_valid():
                print('signos')
                atencion_id = Atencion.objects.get(id=atencion.id)
                presion_arterial = form_signos.cleaned_data.get('presion_arterial')
                frecuencia_cardiaca = form_signos.cleaned_data.get('frecuencia_cardiaca')
                temperatura = form_signos.cleaned_data.get('temperatura')
                frecuencia_respiratoria = form_signos.cleaned_data.get('frecuencia_respiratoria')

                signos = SignosVitales.objects.create(
                    id_atencion=atencion_id,
                    presion_arterial = presion_arterial,
                    frecuencia_cardiaca = frecuencia_cardiaca,
                    temperatura = temperatura,
                    frecuencia_respiratoria = frecuencia_respiratoria,
                )
                signos.save()
                if form_estomatogmatico.is_valid():
                    print('estomatogmatico')
                    tipo = form_estomatogmatico.cleaned_data.get('tipo')
                    detalle = form_estomatogmatico.cleaned_data.get('detalle')

                    estomatogmatico = Estomatogmatico.objects.create(
                        id_atencion=atencion_id,
                        tipo = tipo,
                        detalle = detalle,
                    )
                    estomatogmatico.save()
                    if form_odontograma.is_valid():
                        print('odontograma')
                        diente= form_odontograma.cleaned_data.get('diente')
                        detalle = form_odontograma.cleaned_data.get('detalle')

                        odontograma = Odontograma.objects.create(
                            id_atencion=atencion_id,
                            diente = diente,
                            detalle = detalle,
                        )
                        odontograma.save()

                    return redirect('medico:clientes_medico')

    context = {
        'atencion':form_atencion,
        'estomatogmatico': form_estomatogmatico, 
        'signos': form_signos, 
        'odontograma' : form_odontograma,

    }
    
    return render(request, template_name, context)


def estomatogmatico_view(request,id=None):
    template_name = 'agenda/crear_estomatogmatico.html'
    form = EstomatogmaticoForm(request.POST or None)
    atencion_id = id
    print(historial_id.id)
    if request.method == 'POST':

        if form.is_valid():

            tipo = form.cleaned_data.get('tipo')
            detalle = form.cleaned_data.get('detalle')

            atencion = Atencion.objects.create(
                tipo = consulta,
                detalle = enfermedad,
            )
            atencion.save()
            return redirect('medico:clientes_medico')

    context = {
        'form':form,

    }
    
    return render(request, template_name, context)

def export_recetario_medico(request, id, atencion):
    """
    Exportar recetario medico
    """
    usuario = Usuario.objects.get(id=id)
    historial = get_object_or_404(Historial,cliente=usuario.pk)
    atencion = Atencion.objects.get(Q(id_historial=historial.pk),Q(id=atencion))
    signos = get_object_or_404(SignosVitales,id_atencion=atencion.pk)
    estomatogmatico = get_object_or_404(Estomatogmatico,id_atencion=atencion.pk)
    odontograma = get_object_or_404(Odontograma,id_atencion=atencion.pk)
    print(atencion.pk)
    print(usuario.pk)
    plantilla = 'recetario.odt'

    template_recetario = 'apps/medico/receta/templates/odt/' + plantilla

    template_documento = template_recetario

    
    content_type = FORMATOS_ARCHIVOS.get('PDF').get('content_type')

    now = datetime.now()
    dia = now.day
    mes = now.month
    año = now.year

    data = {
        'u':usuario,
        'd':dia,
        'm':mes,
        'a':año,
        'at': atencion,
        's': signos,
        'es': estomatogmatico,

apps/medico/templates/clientes_medico/listar_clientes.html
{% extends 'base.html' %}
{% load static %}

{%block css_page%}
<link href="{%static 'plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' %}" rel="stylesheet">
<!-- Page plugins css -->
<link href="{%static 'plugins/clockpicker/dist/jquery-clockpicker.min.css' %}" rel="stylesheet">
<!-- Color picker plugins css -->
<link href="{%static 'plugins/jquery-asColorPicker-master/css/asColorPicker.css' %}" rel="stylesheet">
<!-- Date picker plugins css -->
<link href="{%static 'plugins/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet">
<!-- Daterange picker plugins css -->
<link href="{%static 'plugins/timepicker/bootstrap-timepicker.min.css' %}" rel="stylesheet">
<link href="{%static 'plugins/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
{%endblock%}
{% block content-body %}


<div class="content-body">
    
    <div class="row page-titles mx-0">
        <div class="col p-md-0">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
            </ol>
        </div>
    </div>
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Clientes</h4>
                </div>
                <div class="table-responsive">
                    <table class="table table-sm">
                        <thead>
                        <tr>
                            <th>nombres</th>
                            <th>Apellidos</th>
                            <th>Identificacion</th>                             
                            <th>Cita</th>
                            <th>Historia Clinica</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for c in clientes %}
                        <tr>
                            <td><a >{{c.nombres}}</a></td>
                            <td>{{c.apellidos}}</td>
                            <td>{{c.identificacion}}</td>                             
                            <td><a  href="{% url 'medico:citas_cliente_medico' c.id %}" class="btn btn-sm mb-1 btn-light">Citas</a></td>
                            <td><a  href="{% url 'medico:crear_atencion' c.id %}" class="btn btn-sm mb-1 btn-light">Historia</a></td> 
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="bootstrap-pagination">
            <nav>
                {% if is_paginated %}
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number}}" tabindex="-1">Atras</a>
                    </li>
                    {% endif %}
                    {%for pagina in paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a>
                    </li>
                    {% endfor%}
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
                {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>


  {% endblock %}

  {%block js_page%}
  <script src="{% static 'plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' %}"></script>
      <!-- Clock Plugin JavaScript -->
  <script src="{% static 'plugins/clockpicker/dist/jquery-clockpicker.min.js' %}"></script>
  <!-- Color Picker Plugin JavaScript -->
  <script src="{% static 'plugins/jquery-asColorPicker-master/libs/jquery-asColor.js' %}"></script>
  <script src="{% static 'plugins/jquery-asColorPicker-master/libs/jquery-asGradient.js' %}"></script>
  <script src="{% static 'plugins/jquery-asColorPicker-master/dist/jquery-asColorPicker.min.js' %}"></script>
  <!-- Date Picker Plugin JavaScript -->
  <script src="{% static 'plugins/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
  <!-- Date range Plugin JavaScript -->
  <script src="{% static 'plugins/timepicker/bootstrap-timepicker.min.js' %}"></script>
  <script src="{% static 'plugins/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
  
  <script src="{% static 'js/plugins-init/form-pickers-init.js' %}"></script>
  {% endblock %}